# Generated by Django 4.1.3 on 2022-11-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_libros_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
