# Generated by Django 4.1.3 on 2022-11-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_libro_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='path',
            field=models.FileField(upload_to='pdfs'),
        ),
    ]
