# Generated by Django 4.1.3 on 2022-11-16 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_libro_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='user_id',
        ),
    ]
