# Generated by Django 4.1.3 on 2022-11-16 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_libro_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='path',
            new_name='file',
        ),
    ]
