# Generated by Django 4.1.3 on 2022-11-16 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_path_libro_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='title',
        ),
    ]
