# Generated by Django 4.1.3 on 2022-11-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_libro_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='user_id',
        ),
    ]
