# Generated by Django 4.1.3 on 2022-11-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_libro_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='thumbnail',
            field=models.TextField(default='https://res.cloudinary.com/drifqbdtu/image/upload/v1669833009/Lectura/Libro-Abierto-B%C3%A1sico_nqspcx.jpg'),
        ),
    ]
